# Generated by Django 2.2.3 on 2019-07-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField(max_length=2000)),
                ('postcode', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_placed', models.DateTimeField()),
                ('state', models.SmallIntegerField(choices=[(1, 'Placed'), (2, 'Dispatched'), (3, 'Delivered'), (4, 'Cancelled')], default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shoestore.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(max_length=5243000, upload_to='')),
                ('cost_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('selling_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('vat_rate', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=255)),
                ('hexcode', models.CharField(max_length=6)),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='shoestore.Shoe')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shoestore.Order')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoestore.Style')),
            ],
        ),
    ]
