# Generated by Django 2.2.3 on 2019-07-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.ImageField(blank=True, max_length=5243000, upload_to=''),
        ),
    ]
