# Generated by Django 2.2.3 on 2019-07-13 07:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0002_style_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hexcode', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='style',
            name='hexcode',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='vat_rate',
            field=models.DecimalField(choices=[(0, '0%'), (Decimal('0.20'), '20%')], decimal_places=2, default=Decimal('0.20'), max_digits=3),
        ),
        migrations.AlterField(
            model_name='style',
            name='colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='shoestore.Colour'),
        ),
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
