# Generated by Django 2.2.3 on 2019-07-13 08:05

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist

def example_colours(apps, schema_editor):
    examples = [
        ("Black", "000000"),
        ("Suede", "896b41"),
        ("Dark Brown", "654321"),
        ("Teal", "008080")
    ]

    Colour = apps.get_model('shoestore', 'Colour')

    for name, hexcode in examples:
        try:
            Colour.objects.get(name=name)
        except ObjectDoesNotExist:
            c = Colour(name=name, hexcode=hexcode)
            c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shoestore', '0003_auto_20190713_0859'),
    ]

    operations = [
        migrations.RunPython(example_colours),
    ]
